sudo: true

addons:
    apt:
        packages:
            - git
            - curl
            - bzip2
            - zip
            - xz-utils
            - gnupg
            - kpartx
            - dosfstools
            - binutils
            - bc
