sudo: false

script:
    - wget --version
    - ./clean.sh
    - ./update.sh
    - ./build.sh
    - ./buildroot.sh

addons:
    apt:
        packages:
            - git
            - curl
            - bzip2
            - zip
            - xz-utils
            - gnupg
            - kpartx
            - dosfstools
            - binutils
            - bc
