sudo: true

script:
    - ./clean.sh
    - ./update.sh

addons:
    apt:
        packages:
            - git
            - curl
            - bzip2
            - zip
            - xz-utils
            - gnupg
            - kpartx
            - dosfstools
            - binutils
            - bc
