sudo: false

cache:
    directories:
        - packages

script:
    - wget --version
    - rm -rf res/initramfs/boot/config.txt build_dir ./*.zip ./*.xz ./*.bz2
    - ./update.sh
    - ./build.sh
    - ./buildroot.sh

addons:
    apt:
        packages:
            - git
            - curl
            - bzip2
            - zip
            - xz-utils
            - gnupg
            - kpartx
            - dosfstools
            - binutils
            - bc
